DROP TABLE IF EXISTS bars;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
 id BIGSERIAL PRIMARY KEY,
 firstname VARCHAR(255) NOT NULL,
 lastname VARCHAR(255) NOT NULL,
 username VARCHAR(15) NOT NULL UNIQUE,
 email VARCHAR(255) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL
);

CREATE TABLE bars (
 id BIGSERIAL PRIMARY KEY,
 bar_name VARCHAR(140) NOT NULL,
 address TEXT NOT NULL,
 phone_number TEXT NOT NULL,
 website TEXT NOT NULL,
 type_of_bar TEXT NOT NULL,
 user_id INTEGER NOT NULL REFERENCES users (id)
);


